version: "3.8"

services:
  db:
    image: postgis/postgis:latest
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'
  web:
    build: .
    restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data: