# Generated by Django 4.1.5 on 2023-01-27 10:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_culture_season_alter_farmer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='geoapp.culture')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='geoapp.farmer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='geoapp.season')),
            ],
        ),
    ]
